# save as params.yaml in your config directory
amcl:
  ros__parameters:
    use_sim_time: False
    base_frame_id: "base_link"
    global_frame_id: "map"
    odom_frame_id: "odom"

bt_navigator:
  ros__parameters:
    use_sim_time: False

map_server:
  ros__parameters:
    yaml_filename: "/home/omar/maps/my_house.yaml"
    use_sim_time: False

planner_server:
  ros__parameters:
    use_sim_time: False

controller_server:
  ros__parameters:
    use_sim_time: False

recoveries_server:
  ros__parameters:
    use_sim_time: False

local_costmap:
  ros__parameters:
    use_sim_time: False
    global_frame: "odom"
    robot_base_frame: "base_link"
    update_frequency: 5.0
    publish_frequency: 2.0
    width: 3.0
    height: 3.0
    resolution: 0.05
    plugin_names: ["obstacle_layer", "inflation_layer"]
    plugin_types: ["nav2_costmap_2d::ObstacleLayer", "nav2_costmap_2d::InflationLayer"]

global_costmap:
  ros__parameters:
    use_sim_time: False
    global_frame: "map"
    robot_base_frame: "base_link"
    update_frequency: 5.0
    publish_frequency: 2.0
    width: 10.0
    height: 10.0
    resolution: 0.05
    plugin_names: ["static_layer", "obstacle_layer", "inflation_layer"]
    plugin_types: ["nav2_costmap_2d::StaticLayer", "nav2_costmap_2d::ObstacleLayer", "nav2_costmap_2d::InflationLayer"]
