<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- BASE LINK -->

    <link name="base_link">

    </link>

     <!-- BASE_FOOTPRINT Link -->

    <joint name="base_footprint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">

    </link>


    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="-0.1 0 0"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="0.15 0 0.075"/>
            <geometry>
                <box size="0.3 0.3 0.15"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0.15 0 0.075"/>
            <geometry>
                <box size="0.3 0.3 0.15"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="0.3" y="0.3" z="0.15">
            <origin xyz="0.15 0 0.075" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/White</material>
    </gazebo>

    <!-- LEFT WHEEL LINK -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 0.175 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>




    <!-- RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 -0.175 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>


    <!-- CASTER WHEEL LINK -->

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel"/>
        <origin xyz="0.24 0 0"/>
    </joint>


    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="0.05"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.05"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="0.1" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel">
        <material>Gazebo/Black</material>
        <mu1 value="0.0005"/>
        <mu2 value="0.0005"/>
    </gazebo>





  <xacro:macro name="lifter_transmission" params="joint_name actuator_name">
    <transmission name="${joint_name}_transmission">
        <plugin>transmission_interface/SimpleTransmission</plugin>
        <actuator name="${actuator_name}" role="actuator1"/>
        <joint name="${joint_name}" role="joint1">
            <mechanical_reduction>1.0</mechanical_reduction>
        </joint>
    </transmission>
  </xacro:macro>


  <xacro:property name="screw_diameter" value="0.008" />
  <xacro:property name="screw_length" value="0.10" />
  <xacro:property name="plate_radius" value="0.045" />

    <!-- Link for the platform mid -->
  <link name="link_platform_mid">
    <origin xyz="0 0 0.0" rpy="0 0 0"/>
    <visual>
      <geometry>
        <mesh filename="package://my_bot/meshes/Lead_screw.STL" scale="0.001 0.001 0.001" />
      </geometry>
      <material name="black">
        <color rgba="0.1 0.1 0.1 1" />
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.02 0.02 0.10" />
      </geometry>
    </collision>
    <inertial>
      <mass value="1"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0"
               iyy="1.0" iyz="0.0"
               izz="1.0"/>
    </inertial>
  </link>

  <!-- Joint connecting upper link to platform mid -->
  <joint name="platform_joint" type="fixed">
    <parent link="chassis" />
    <child link="link_platform_mid" />
    <origin xyz="0.0 0 0.02" rpy="0 0 0"/>
  </joint>

  <!-- Link for the lift mechanism -->
  <link name="lift_link">
    <visual>
      <origin xyz="-${plate_radius/1.1} -${plate_radius/1.1}  0.0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://arduinobot_description/meshes/upperstand.STL" scale="0.001 0.001 0.001" />
      </geometry>
      <material name="black">
        <color rgba="0.1 0.1 0.1 1" />
      </material>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://my_bot/meshes/upperstand.STL" scale="0.001 0.001 0.001" />
      </geometry>
    </collision>
    <inertial>
      <mass value="1"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0"
               iyy="1.0" iyz="0.0"
               izz="1.0"/>
    </inertial>
  </link>

  <!-- Prismatic joint for lifting -->
  <joint name="lift_joint" type="prismatic">
    <origin xyz="0 0 0.03" rpy="0 0 0"/>
    <parent link="link_platform_mid" />
    <child link="lift_link" />
    <axis xyz="0 0 1" rpy="0 0 0"/>
    <limit effort="100.0" lower="-0.05" upper="0.035" velocity="1.0"/>
    <dynamics damping="0.1" friction="0.1"/>
    <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
  </joint>

 <!-- Use the lifter transmission macro for lift_joint -->
 <lifter_transmission joint_name="lift_joint" actuator_name="lifter_motor"/>

</robot>