<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.317" />
    <xacro:property name="base_width" value="0.212" />
    <xacro:property name="base_height" value="0.0446" />
    <xacro:property name="upper_length" value="0.317" />
    <xacro:property name="upper_width" value="0.212" />
    <xacro:property name="upper_height" value="0.0423" />
    <xacro:property name="wheel_radius" value="0.0325" />
    <xacro:property name="robot_height" value="0.0869" />
    <xacro:property name="wheel_length" value="0.028" />
    <xacro:property name="to_wheel_center" value="0.07" />

    <link name="base_footprint" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${robot_height}" />
            </geometry>
            <origin xyz="0 0 ${robot_height / 2.0}" rpy="0 0 0" />
          <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${robot_height}" />
            </geometry>
            <origin xyz="0 0 ${robot_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5.0" l="${2*base_length}" w="${2*base_width}" h="${2*robot_height}"
                           xyz="0 0 ${robot_height / 2.0}" rpy="0 0 0" />
    </link>


    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${2*wheel_radius}" h="${2*wheel_length}" 
                                    xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="front_right" />
    <xacro:wheel_link prefix="front_left" />
    <xacro:wheel_link prefix="back_right" />
    <xacro:wheel_link prefix="back_left" />



    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <joint name="front_wheel_right_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_right_wheel_link" />
        <origin xyz="${-base_length / 2.7} ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="front_wheel_left_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_left_wheel_link" />
        <origin xyz="${-base_length / 2.7} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>
    <joint name="back_wheel_right_joint" type="continuous">
        <parent link="base_link" />
        <child link="back_right_wheel_link" />
        <origin xyz="${base_length / 2.7} ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="back_wheel_left_joint" type="continuous">
        <parent link="base_link" />
        <child link="back_left_wheel_link" />
        <origin xyz="${base_length / 2.7} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

</robot>