controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    robitcubebot_controller:
      type: diff_drive_controller/DiffDriveController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    simple_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    odom_publisher:
      type: diff_drive_controller/OdometryPublisher
      publish_rate: 50
      base_frame_id: base_footprint
      odom_frame_id: odom
      robot_base_frame_id: base_footprint
      left_wheel_names  : ['back_wheel_left_joint']
      right_wheel_names : ['back_wheel_right_joint']


    lifter_controller:
      type: velocity_controllers/JointGroupVelocityController
      joints:  # Changed 'joint' to 'joints' to match expected parameter
        - lift_joint
      position_gains:
        lift_joint: { p: 100.0 }
      max_velocity: 0.05



robitcubebot_controller:
  ros__parameters:
    type        : diff_drive_controller/DiffDriveController
    use_stamped_vel: true
    left_wheel_names  : ['front_wheel_left_joint','back_wheel_left_joint']
    right_wheel_names : ['front_wheel_right_joint','back_wheel_right_joint']

    publish_rate: 50.0               # default: 50
    pose_covariance_diagonal : [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]

    wheel_separation : 0.24
    wheel_radius : 0.033

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 0.5

    # Base frame_id
    base_frame_id: base_footprint #default: base_link

    # Publish limited velocity
    publish_limited_velocity: true

    # Publish wheel data
    publish_wheel_data: true

    # Publish to TF directly or not
    enable_odom_tf: true

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 1.0  # m/s
        min_velocity           : -0.5 # m/s
        has_acceleration_limits: true
        max_acceleration       : 0.8  # m/s^2
        min_acceleration       : -0.4 # m/s^2
        has_jerk_limits        : false
        max_jerk               : 5.0  # m/s^3
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 2.5  # rad/s
        has_acceleration_limits: true
        max_acceleration       : 2.3 # rad/s^2
        has_jerk_limits        : false
        max_jerk               : 2.5  # rad/s^3



gripper_controller:
  ros__parameters:
    joints:
      - lift_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    open_loop_control: true
    allow_integration_in_goal_trajectories: true

simple_velocity_controller:
  ros__parameters:
    joints:
     - front_wheel_right_joint
     - back_wheel_right_joint
     - front_wheel_left_joint
     - back_wheel_left_joint

odom_publisher:
  ros__parameters:
    type: diff_drive_controller/OdometryPublisher
    publish_rate: 50
    base_frame_id: base_footprint
    odom_frame_id: odom
    robot_base_frame_id: base_footprint
    left_wheel_names  : ['back_wheel_left_joint']
    right_wheel_names : ['back_wheel_right_joint']

joint_state_broadcaster:
  ros__parameters:
    joints:
      - front_wheel_right_joint
      - back_wheel_right_joint
      - front_wheel_left_joint
      - back_wheel_left_joint
      - lift_joint



# LiDAR configuration
lidar:
  ros__parameters:
    scan_topic: "/scan"
    frame_id: "laser_frame"
    min_range: 0.12
    max_range: 3.5
    update_rate: 30.0
